/**
 * Every pre-rendered sprite in public/sprites, defined for the recap's
 * knowledge graph. Not queried live — this mirrors the bundled Magic
 * Patterns catalog closely enough for a fun visual, without pulling the
 * (heavy) sprite React components into the client bundle.
 */
export const COMPONENT_IDS: readonly string[] = [
  "cloth-belt",
  "cloth-boot",
  "cloth-cap",
  "cloth-coat-hanger",
  "cloth-flip-flop",
  "cloth-glove",
  "cloth-jacket",
  "cloth-scarf",
  "cloth-sock",
  "cloth-sunglasses",
  "cloth-swim-ring",
  "cloth-t-shirt",
  "cloth-top-hat",
  "cloth-trainer",
  "cloth-wristwatch",
  "collectible-battery",
  "collectible-coin",
  "collectible-gem",
  "collectible-key",
  "decor-finish-flag",
  "enemy-turret",
  "food-apple",
  "food-banana-peel",
  "food-burger",
  "food-carrot",
  "food-cheese",
  "food-coffee-cup",
  "food-cupcake",
  "food-donut",
  "food-egg",
  "food-hot-dog",
  "food-ice-cream",
  "food-lollipop",
  "food-pizza-slice",
  "food-popcorn",
  "food-soda-can",
  "food-sushi",
  "food-taco",
  "food-watermelon",
  "fur-bed",
  "fur-ceiling-fan",
  "fur-curtain",
  "fur-desk",
  "fur-door",
  "fur-filing-cabinet",
  "fur-mirror",
  "fur-picture-frame",
  "fur-potted-plant",
  "fur-rug",
  "fur-sofa",
  "fur-step-ladder",
  "fur-stool",
  "fur-wardrobe",
  "fur-window",
  "house-bathtub",
  "house-bin",
  "house-birthday-cake",
  "house-candle",
  "house-fire-extinguisher",
  "house-gift-box",
  "house-iron",
  "house-key-ring",
  "house-laundry-basket",
  "house-party-balloons",
  "house-party-hat",
  "house-piggy-bank",
  "house-post-box",
  "house-soap-bar",
  "house-toilet-roll",
  "house-toothbrush",
  "house-towel",
  "house-wallet",
  "house-washing-machine",
  "kit-blender",
  "kit-bottle",
  "kit-cereal-box",
  "kit-cooking-pot",
  "kit-cutting-board",
  "kit-fork",
  "kit-fridge",
  "kit-frying-pan",
  "kit-kettle",
  "kit-knife",
  "kit-microwave",
  "kit-mug",
  "kit-plate",
  "kit-rolling-pin",
  "kit-tin-can",
  "kit-toaster",
  "kit-water-bottle",
  "mechanic-exit-door",
  "mechanic-portal-gate",
  "mus-cassette-tape",
  "mus-drum",
  "mus-guitar",
  "mus-harmonica",
  "mus-maracas",
  "mus-microphone",
  "mus-piano-keys",
  "mus-tambourine",
  "mus-trumpet",
  "mus-vinyl-record",
  "mus-violin",
  "mus-xylophone",
  "out-anthill",
  "out-beach-ball",
  "out-beehive",
  "out-cactus",
  "out-feather",
  "out-flower",
  "out-lightning",
  "out-log",
  "out-mushroom-cluster",
  "out-nest",
  "out-puddle",
  "out-rainbow",
  "out-sandcastle",
  "out-seashell",
  "out-snowman",
  "out-tree-stump",
  "sport-baseball-bat",
  "sport-basketball",
  "sport-bicycle",
  "sport-bowling-ball",
  "sport-bowling-pin",
  "sport-boxing-glove",
  "sport-dumbbell",
  "sport-football",
  "sport-frisbee",
  "sport-helmet",
  "sport-hockey-stick",
  "sport-jump-rope",
  "sport-roller-skate",
  "sport-skateboard",
  "sport-skis",
  "sport-surfboard",
  "sport-tennis-racket",
  "sport-yoga-mat",
  "stat-alarm-clock",
  "stat-backpack",
  "stat-book",
  "stat-calculator",
  "stat-eraser",
  "stat-globe",
  "stat-notebook",
  "stat-paperclip",
  "stat-pen",
  "stat-pencil",
  "stat-ruler",
  "stat-scissors",
  "stat-stapler",
  "stat-sticky-note",
  "stat-tape-roll",
  "stat-whiteboard",
  "tech-boombox",
  "tech-camera",
  "tech-computer-mouse",
  "tech-desk-lamp",
  "tech-earbud-case",
  "tech-earbud-case-open",
  "tech-earbuds",
  "tech-game-controller",
  "tech-headphones",
  "tech-keyboard",
  "tech-laptop",
  "tech-light-bulb",
  "tech-phone-bounce-pad",
  "tech-router",
  "tech-smartphone",
  "tech-speaker",
  "tech-tablet",
  "tech-television",
  "tech-vacuum-cleaner",
  "tech-wall-clock",
  "tool-broom",
  "tool-bucket",
  "tool-chain",
  "tool-flashlight",
  "tool-hammer",
  "tool-handsaw",
  "tool-nail",
  "tool-paint-brush",
  "tool-paint-bucket",
  "tool-plunger",
  "tool-power-drill",
  "tool-rope-coil",
  "tool-screwdriver",
  "tool-shovel",
  "tool-tape-measure",
  "tool-toolbox",
  "tool-watering-can",
  "tool-wrench",
  "toy-action-figure",
  "toy-bubble-wand",
  "toy-building-brick",
  "toy-dice",
  "toy-jack-in-the-box",
  "toy-kite",
  "toy-marble",
  "toy-pinwheel",
  "toy-playing-cards",
  "toy-puzzle-piece",
  "toy-rubber-duck",
  "toy-spinning-top",
  "toy-teddy-bear",
  "toy-toy-car",
  "toy-yo-yo",
  "veh-aeroplane",
  "veh-boat",
  "veh-bus",
  "veh-car",
  "veh-fuel-pump",
  "veh-helicopter",
  "veh-hot-air-balloon",
  "veh-motorcycle",
  "veh-rocket",
  "veh-scooter",
  "veh-shopping-trolley",
  "veh-traffic-cone",
  "veh-traffic-light",
  "veh-train",
  "veh-truck",
  "veh-tyre",
  "veh-wheelbarrow",
];

/** "cloth-t-shirt" -> "T shirt" */
export function componentLabel(id: string): string {
  const rest = id.split("-").slice(1).join(" ");
  if (!rest) return id;
  return rest.charAt(0).toUpperCase() + rest.slice(1);
}

/** Game titles for the recap's component usage cards. */
const PLACEHOLDER_GAME_TITLES = [
  "Cereal Aisle Dash",
  "Rooftop Rush",
  "Garage Sale Gauntlet",
  "Midnight Snack Attack",
  "Sock Drawer Escape",
  "Backyard Blitz",
  "Toy Box Uprising",
  "Kitchen Chaos",
  "Attic Ascent",
  "Laundry Day Larceny",
  "Bookshelf Breakout",
  "Garden Gauntlet",
  "Workshop Wipeout",
  "Playroom Pandemonium",
  "Closet Crawl",
  "Desk Defender",
  "Pantry Panic",
  "Bathroom Blitz",
  "Living Room Legends",
  "Bedroom Bounce",
];

function hashString(value: string): number {
  let hash = 0;
  for (let index = 0; index < value.length; index += 1) {
    hash = (hash << 5) - hash + value.charCodeAt(index);
    hash |= 0;
  }
  return Math.abs(hash);
}

/** Deterministic "used in these games" list derived from component usage data. */
export function placeholderGamesFor(componentId: string): string[] {
  const seed = hashString(componentId);
  const count = seed % 5; // 0–4, so some components show up empty
  const start = seed % PLACEHOLDER_GAME_TITLES.length;
  const titles: string[] = [];
  for (let index = 0; index < count; index += 1) {
    titles.push(
      PLACEHOLDER_GAME_TITLES[(start + index * 3) % PLACEHOLDER_GAME_TITLES.length],
    );
  }
  return titles;
}
